server:
  port: 9015

eureka:
  instance:
    hostname: localhost
    appname: F0015
  client:
    service-url:
      defaultZone: http://localhost:9014/eureka/
#spring:
#  application:
#    name: F0015