server:
  port: 9016
eureka:
  instance:
    hostname: localhost
    appname: F0016
  client:
    service-url:
      defaultZone: http://localhost:9014/eureka/
ribbon:
  eureka:
    enabled: true
#spring:
#  application:
#    name: F0016
